### ISSUE TITLE
Python bottle in virtual environment from travis

### ISSUE THREAD

**Issue by panageo** [intracom-telecom-sdn/multinet#37]
The python bottle library inside the deploy/requirements.txt is not working from the virtual environment in travis. It works though from virtual machines deploied with the /deploy/provision.sh script, that is responsible for the creation of the virtual environment. 

As a workaround we install bottle in travis.yml manually with apt-get install python-bottle

**Comment by konstantinos-papadopoulos** [comment]
Build passed
-https://github.com/intracom-telecom-sdn/multinet/commit/86c760ea3298b015c33c7610a20d6deebf127acb
-https://travis-ci.org/intracom-telecom-sdn/multinet/builds/165450619
